package bob.ui;

import java.util.List;
import java.util.Map;
import java.util.Scanner;

import bob.task.Task;
import bob.task.TaskList;

/**
 * Handles interactions with the user, such as reading input and displaying
 * messages.
 */
public class Ui {
    private static final String HORIZONTAL_LINE = "_".repeat(30);
    private final Scanner scanner;
    private String lastResponse = "";

    /**
     * Constructs a new Ui instance with standard input scanner.
     */
    public Ui() {
        this.scanner = new Scanner(System.in);
    }

    /**
     * Displays the welcome greeting to the user.
     */
    public void showWelcome() {
        String message = "Hello! I'm Bob.\nWhat can I do for you?";
        this.lastResponse = message;
        showDividerLine();
        System.out.println(message);
        showDividerLine();
    }

    /**
     * Displays the goodbye message to the user.
     */
    public void showGoodbye() {
        String message = "Goodbye.";
        this.lastResponse = message;
        System.out.println(message);
    }

    /**
     * Prints a horizontal divider line.
     */
    public void showDividerLine() {
        System.out.println(HORIZONTAL_LINE);
    }

    /**
     * Reads a line of user input.
     *
     * @return the command string entered by the user
     */
    public String readCommand() {
        return scanner.nextLine();
    }

    /**
     * Checks if there is another line of input available.
     *
     * @return true if there is input available, false otherwise
     */
    public boolean hasNextCommand() {
        return scanner.hasNextLine();
    }

    /**
     * Displays the full list of tasks.
     *
     * @param tasks the task list to display
     */
    public void showTaskList(TaskList tasks) {
        StringBuilder sb = new StringBuilder("Tasks:\n");
        for (int i = 0; i < tasks.size(); i++) {
            sb.append(String.format("%d: %s", i + 1, tasks.get(i).toString()));
            if (i < tasks.size() - 1) {
                sb.append("\n");
            }
        }
        this.lastResponse = sb.toString();
        System.out.println(this.lastResponse);
    }

    /**
     * Displays the tasks that match a search keyword with their original list
     * indices.
     *
     * @param matchingEntries the list of entries containing 1-based indices and
     *                        matching tasks
     */
    public void showMatchingTasks(List<Map.Entry<Integer, Task>> matchingEntries) {
        StringBuilder sb = new StringBuilder("Here are the matching tasks in your list:\n");
        for (int i = 0; i < matchingEntries.size(); i++) {
            Map.Entry<Integer, Task> entry = matchingEntries.get(i);
            sb.append(String.format("%d.%s", entry.getKey(), entry.getValue().toString()));
            if (i < matchingEntries.size() - 1) {
                sb.append("\n");
            }
        }
        this.lastResponse = sb.toString();
        System.out.println(this.lastResponse);
    }

    /**
     * Displays the message after adding a task.
     *
     * @param task       the added task
     * @param totalCount the total number of tasks after addition
     */
    public void showTaskAdded(Task task, int totalCount) {
        String message = String.format("Task added:\n%s\n%d %s in list",
                task.toString(), totalCount, totalCount < 2 ? "item" : "items");
        this.lastResponse = message;
        System.out.println(message);
    }

    /**
     * Displays the message after deleting a task.
     *
     * @param task       the deleted task
     * @param totalCount the total number of tasks after deletion
     */
    public void showTaskDeleted(Task task, int totalCount) {
        String message = String.format("Removed: \n%s\n%d %s in list",
                task.toString(), totalCount, totalCount < 2 ? "item" : "items");
        this.lastResponse = message;
        System.out.println(message);
    }

    /**
     * Displays the message after marking or unmarking a task.
     *
     * @param task   the task that was marked or unmarked
     * @param isDone true if marked as done, false if marked as not done
     */
    public void showTaskMarked(Task task, boolean isDone) {
        String status = isDone ? "Marked as done:" : "Marked as not done:";
        String message = status + "\n " + task.toString();
        this.lastResponse = message;
        System.out.println(message);
    }

    /**
     * Displays a message to the user.
     *
     * @param message the message to display
     */
    public void showMessage(String message) {
        this.lastResponse = message;
        System.out.println(message);
    }

    /**
     * Displays an error message to the user.
     *
     * @param message the error message to display
     */
    public void showError(String message) {
        this.lastResponse = message;
        System.out.println(message);
    }

    /**
     * Returns the most recent response message generated by the UI.
     *
     * @return the last generated response string
     */
    public String getLastResponse() {
        return lastResponse;
    }

    /**
     * Closes the underlying scanner resource.
     */
    public void close() {
        scanner.close();
    }
}
